export const GET_POKEMON_REQUEST = "GET_POKEMON_REQUEST";
export const GET_POKEMON_SUCCESS = "GET_POKEMON_SUCCESS";
export const GET_POKEMON_FAIL = "GET_POKEMON_FAIL";

export const GET_POKEMON_IMG_BY_ID_REQUEST = "GET_POKEMON_IMG_BY_ID_REQUEST";
export const GET_POKEMON_IMG_BY_ID_SUCCESS = "GET_POKEMON_IMG_BY_ID_SUCCESS";
export const GET_POKEMON_IMG_BY_ID_FAIL = "GET_POKEMON_IMG_BY_ID_FAIL";
